<?php

!defined('R_P') && exit('Forbidden!');

$source_version = 'discuz x1.5'; //版本号

$compile_type = 'mysql';

$step_data = array(
	'1'	=> '用户数据合并和统计',//pw_members、pw_memberdata、pw_memberinfo
	'2' => '用户头像',
	'3' => '活动附件',//pw_actattachs
	'4' => '群组活动',//pw_active
	'5' => '活动贴信息',//pw_activity
	'6' => '活动帖报名信息表',//pw_activitymembers 
	'7' => '活动支付记录',// pw_activitypaylog
	'8' => '活动贴报名成员',//pw_actmember 
	'9' => '群组活动报名',//pw_actmembers 
	'10' => '论坛管理组信息 ',//pw_administrators 
	'11' => '前台管理安全日志记录 ',//pw_adminlog 
	'12' => '系统广告信息',//pw_advert 
	'13' => '门户权限表',//pw_area_level 
	'14' => '附件出售信息',//pw_attachbuy 
	'15' => '版块下载附件扣除积分记录',//pw_attachdownload 
	'16' => '附件主表信息 ',//pw_attachs 
	'17' => '我关注的朋友数据',//pw_attention 
	'18' => '关注禁言用户列表',// pw_attention_blacklist 
	'19' => '禁止数据表',//pw_ban 
	'20' => '禁言用户列表',//pw_banuser 
	'21' => '论坛基本信息',// pw_bbsinfo 
	'22' => '广告出租信息',//pw_buyadvert 
	'23' => '后台定单管理相关数据',//pw_clientorder 
	'24' => '群组成员信息 ',//pw_cmembers 
	'25' => '文章表',//pw_cms_article 
	'26' => '文章权限表',//pw_cms_purview 
	'27' => '群组相册',//pw_cnalbum 
	'28' => '群组相片',//pw_cnphoto 
	'29' => '收藏表',//pw_collection 
	'30' => '收藏分类表 ',//pw_collectiontype
	'31' => '群组信息',//pw_colonys 
	'32' => '用户评论表',//pw_comment 
	'33' => '积分日志表',//pw_creditlog 
	'34' => '群组记录表',//pw_cwritedata 
	'35' => '辩论记录',//pw_debatedata 
	'36' => '辩论帖子记录',//pw_debates 
	'37' => '日志主表',//pw_diary 
	'38' => '日志个人分类表',//pw_diarytype 
	'39' => '用户草稿箱信息',//pw_draft 
	'40' => '购买组相关信息',//pw_extragroups 
	'41' => '个人收藏夹',//pw_favors 
	'42' => '好友动态表 ',//pw_feed 
	'43' => '敏感词记录表',//pw_filter 
	'44' => '版块日志数据(转帐功能日志)',//pw_forumlog 
	'45' => '版主管理记录',//pw_forummsg 
	'46' => '版块数据',//pw_forums 
	'47' => '版块访问权限出售设置',//pw_forumsell 
	'48' => '好友功能相关信息',//pw_friends 
	'49' => '好友功能相关信息',//pw_friendtype 
	'50' => '群组回复结构表',//pw_group_replay 
	'51' =>	'邀请码功能相关',//pw_invitecode 
	'52' =>	'好友邀请宣传奖励记录表',//pw_inviterecord 
	'53' => '任务申请表',//pw_jober 
	'54' => '勋章操作信息',// pw_medalslogs 
	'55' => '用户勋章记录表',//pw_medaluser 
	'56' => '用户的自定义积分',//pw_membercredit 
	'57' => '用户基本信息',//pw_memberdata 
	'58' => '用户相关信息',//pw_memberinfo 
	'59' => '会员主信息表',//pw_members 
	'60' => '后台管理便笺信息',//pw_memo
	'61' => '消息中心附件表',//pw_ms_attachs 
	'62' => '消息配置表',//pw_ms_configs 
	'63' => '消息体表',//pw_ms_messages 
	'64' => '消息关系体表',//pw_ms_relations 
	'65' => '消息回复表',//pw_ms_replies 
	'66' => '消息中心搜索关系表',//pw_ms_searchs 
	'67' => '圈子留言表',//pw_oboard 
	'68' => '圈子用户相关表',//pw_ouserdata 
	'69' => '圈子记录表',//pw_owritedata 
	'70' => '团购活动报名信息表 ',//pw_pcmember 
	'71' => '权限表',//pw_permission 
	'72' => '回复贴信息表',//pw_posts 
	'73' => '空间隐私表',//pw_privacy 
	'74' => '模板自定义推送数据表',//pw_pushdata 
	'75' => '门户推送上传图片',//pw_pushpic 
	'76' => '评价统计表',//pw_rate 
	'77' => '评价配置表',//pw_rateconfig 
	'78' => '删除帖子相关信息',//pw_recycle 
	'79' => '帖子报告信息',//pw_report 
	'80' => '悬赏贴',//pw_reward 
	'81' => '会员分享表',//pw_sharelinks 
	'82' => '用户指定版块权限',//pw_singleright 
	'83' => '个人空间信息表',//pw_space 
	'84' => '专题分类表',//pw_stopiccategory 
	'85' => '专题背景图片表',//pw_stopicpictures 
	'86' => '论坛风格主表',//pw_styles 
	'87' => '帖子基本信息表',//pw_threads 
	'88' => '道具操作相关信息(与交易币相关)',//pw_toollog 
	'89' => '交易帖子信息',//pw_trade 
	'90' => '交易记录表',//pw_tradeorder 
	'91' => '用户中心同步积分通知队列',//pw_ucsyncredit 
	'92' => '用户添加的应用的数据表',//pw_userapp 
	'93' => '用户帐号绑定/切换',//pw_userbinding 
	'94' => '用户数据缓存表',//pw_usercache 
	'95' => '道具交易数据信息',//pw_usertool 
	'96' => '会员投票表',//pw_voter 
	'97' => '新鲜事评论关系表',//pw_weibo_cmrelations 
	'98' => '新鲜事评论表',//pw_weibo_comment 
	'99' => '新鲜事内容表',//pw_weibo_content 
	'100' => '新鲜事@我的关联表',//pw_weibo_referto 
	'101' => '我关注的新鲜事关系表',//pw_weibo_relations 
);
?>